version: '3'

services:
  gps:
    image: bradsjm/rpi-gpsd
    build: https://github.com/bradsjm/Dockerfiles.git#:rpi-gpsd
    container_name: gps
    devices:
      - '/dev/ttyAMA0:/dev/ttyAMA0'
    ports:
      - '2947:2947'
    command: '-D2 /dev/ttyAMA0'
    tmpfs: '/run'
    network_mode: bridge
    restart: unless-stopped

  ntp:
    image: bradsjm/rpi-chrony
    build: https://github.com/bradsjm/Dockerfiles.git#:rpi-chrony
    container_name: ntp
    depends_on:
      - gps
    devices:
      - '/dev/pps0:/dev/pps0'
    ports:
      - '123:123/udp'
    ipc: 'container:gps'
    tmpfs: '/run'
    cap_add:
      - SYS_TIME
    network_mode: bridge
    restart: unless-stopped

  dump1090:
    image: bradsjm/rpi-dump1090-fa
    build: https://github.com/bradsjm/Dockerfiles.git#:rpi-dump1090-fa
    container_name: dump1090
    devices:
      - '/dev/bus/usb:/dev/bus/usb'
    ports:
      - '30001-30005:30001-30005'
      - '30104:30104'
    network_mode: bridge
    command: '--device 00001000 --quiet --net --gain -10 --lat 32.79391 --lon -96.80642'
    restart: unless-stopped

  piaware:
    image: bradsjm/rpi-piaware
    build: https://github.com/bradsjm/Dockerfiles.git#:rpi-piaware
    mac_address: 02:42:ac:12:00:05
    container_name: piaware
    ports:
      - '30105:30105'
    network_mode: bridge
    tmpfs: '/run'
    environment:
      - USER=xxxxxxx
      - PASSWORD=xxxxxxx
      - FEEDID=
      - GPSD=gps
    links:
      - dump1090
      - gps
    restart: unless-stopped

  exchange-adsb:
    image: bradsjm/rpi-socat
    build: https://github.com/bradsjm/Dockerfiles.git#:rpi-socat
    container_name: exchange-adsb
    network_mode: bridge
    links:
      - dump1090
    command: '-u TCP:dump1090:30005 TCP:feed.adsbexchange.com:30005'
    read_only: true
    restart: unless-stopped

  exchange-mlat:
    image: bradsjm/rpi-mlat-client
    build: https://github.com/bradsjm/Dockerfiles.git#:rpi-mlat-client
    container_name: exchange-mlat
    network_mode: bridge
    ports:
      - '30205:30205'
    links:
      - dump1090
    command: '--input-type dump1090 --input-connect dump1090:30005 --lat 32.79391 --lon -96.80642 --alt 191 --user bradsjm --server feed.adsbexchange.com:31090 --no-udp --results beast,listen,30205'
    restart: unless-stopped

  telegraf:
    image: bradsjm/rpi-telegraf:latest
    hostname: pi
    container_name: telegraf
    network_mode: bridge
    restart: unless-stopped
    environment:
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
    volumes:
      - '/root/telegraf.conf:/etc/telegraf/telegraf.conf:ro'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/var/run/utmp:/var/run/utmp:ro'
      - '/sys:/rootfs/sys:ro'
      - '/proc:/rootfs/proc:ro'
      - '/etc:/rootfs/etc:ro'