version: '3'

volumes:
  downloads:
  sonarr:
  plex:
  plexpy:
  transcode:
  nzbget:
  radarr:
  media:
    driver: local
    driver_opts:
      type: nfs
      o: proto=tcp,addr=172.16.100.1,rw
      device: ":/mnt/Data/Media"

services:
  plex:
    image: plexinc/pms-docker:plexpass
    container_name: plex
    network_mode: host
    restart: unless-stopped
    volumes:
      - 'plex:/config'
      - 'transcode:/transcode'
      - 'media:/media'
    environment:
      - 'TZ=America/Chicago'
      - 'PLEX_UID=1000'
      - 'PLEX_GID=1000'
      - 'VERSION=latest'

  plexpy:
    image: 'linuxserver/plexpy:latest'
    container_name: plexpy
    network_mode: bridge
    restart: unless-stopped
    volumes:
      - 'plexpy:/config'
      - 'plex:/plex:ro'
    environment:
      - 'TZ=America/Chicago'
      - 'PUID=1000'
      - 'PGID=1000'
    ports:
      - '8181:8181/tcp'

  nzbget:
    image: 'linuxserver/nzbget:latest'
    container_name: 'nzbget'
    network_mode: bridge
    restart: unless-stopped
    volumes:
      - 'nzbget:/config'
      - 'downloads:/downloads'
    environment:
      - 'TZ=America/Chicago'
      - 'PUID=1000'
      - 'PGID=1000'
    ports:
      - '6789:6789/tcp'

  sonarr:
    image: 'linuxserver/sonarr:latest'
    container_name: 'sonarr'
    network_mode: bridge
    restart: unless-stopped
    volumes:
      - '/dev/rtc:/dev/rtc:ro'
      - 'sonarr:/config'
      - 'downloads:/downloads'
      - 'media:/tv'
    environment:
      - 'TZ=America/Chicago'
      - 'PUID=1000'
      - 'PGID=1000'
    ports:
      - '8989:8989/tcp'
    links:
      - nzbget
      - transmission

  radarr:
    image: 'linuxserver/radarr:latest'
    container_name: 'radarr'
    network_mode: bridge
    restart: unless-stopped
    volumes:
      - '/dev/rtc:/dev/rtc:ro'
      - 'radarr:/config'
      - 'downloads:/downloads'
      - 'media:/movies'
    environment:
      - 'TZ=America/Chicago'
      - 'PUID=1000'
      - 'PGID=1000'
    ports:
      - '7878:7878/tcp'
    links:
      - nzbget
      - transmission

  transmission:
    image: 'haugene/transmission-openvpn:latest'
    container_name: 'transmission'
    network_mode: bridge
    privileged: true
    restart: unless-stopped
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - 'downloads:/data'
    environment:
      - 'OPENVPN_PROVIDER=PIA'
      - 'OPENVPN_CONFIG=CA North York'
#     - 'OPENVPN_USERNAME='
#     - 'OPENVPN_PASSWORD='
      - 'LOCAL_NETWORK=172.16.1.0/24'
      - 'TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=true'
      - 'TRANSMISSION_RATIO_LIMIT_ENABLED=true'
      - 'PUID=1000'
      - 'PGID=1000'
    env_file: ./openvpn.env
    ports:
      - '9091:9091/tcp'