version: '3'

services:
  crashplan:
    image: 'gfjardim/crashplan:latest'
    container_name: 'crashplan'
    network_mode: host
    restart: unless-stopped
    volumes:
      - 'crashplan-config:/config'
      - '/mnt:/backup'
    environment:
      - 'TZ=America/Chicago'
      - 'USER_ID=0'
      - 'GROUP_ID=0'
    deploy:
      placement:
        constraints: [node.platform.os == linux]

  weewx:
    image: 'bradsjm/weewx:3.6.2'
    container_name: 'weewx'
    network_mode: bridge
    restart: unless-stopped
    environment:
      - 'TZ=America/Chicago'
    deploy:
      placement:
        constraints: [node.platform.os == linux]

  hs3:
    image: 'bradsjm/homeseer3:latest'
    container_name: 'hs3'
    network_mode: host
    restart: unless-stopped
    volumes:
      - 'hs3-config:/data'
    deploy:
      placement:
        constraints: [node.platform.os == linux]

  vrs:
    image: 'bradsjm/virtualradarserver:preview'
    container_name: 'vrs'
    network_mode: bridge
    restart: unless-stopped
    volumes:
      - 'vrs-config:/config'
    deploy:
      placement:
        constraints: [node.platform.os == linux]
